### ISSUE TITLE
Can support nested object?

### ISSUE THREAD

**Issue by chainchelliah** [DavBfr/simple_mustache#1]
I know it's a simple one, but out of curiosity, I'm asking this. 
If not any other libs available for a flutter or how to achieve it.

Thanks

**Comment by DavBfr** [comment]
Yes, I think you can use nested objects.

**Comment by chainchelliah** [comment]
Thanks for your response. 
I tried the below one and it is not rendering as expected. 
_'Hello, my name is {{contact.name}}!'_ 
I used dot case. Am I doing it in the correct way?

**Comment by DavBfr** [comment]
Ok, that's what you mean by nested. No, it does not support that.
